parameters:
  screeper.server.parameters.servers: ~

services:
    screeper.server.services.server:
        class: Screeper\ServerBundle\Services\ServerService
        arguments:
            - '@service_container'